### ISSUE TITLE
RetroPlayer roadmap

### ISSUE THREAD

**Issue by garbear** [garbear/xbmc#80]
Target: v18.0

## RetroPlayer tasks
- [ ] **General**
    - [ ] Fix loading game add-ons on Android
- [ ] **Game saves**
    - [ ] Memory saves (savestates) (https://github.com/xbmc/xbmc/pull/11034)
    - [ ] In-game saves (SRAM saves) (https://github.com/xbmc/xbmc/pull/11380)
- [ ] **BIOS support**
    - [ ] libretro VFS support (https://github.com/libretro/RetroArch/pull/3715)
    - [ ] Package BIOS add-ons
- [ ] **Parse extensions** where VideoPlayer conflicts with RetroPlayer
    - [ ] .zip
    - [ ] .iso
    - [ ] .img
    - [ ] .bin
    - [ ] .cue
- [ ] **Multiplayer**
    - [ ] Game streaming
        - [ ] Fix OpenSSL dependency in game.moonlight on all platforms
    - [ ] Save states
    - [ ] Achievements

**Comment by sigboe** [comment]
Hi @garbear been subscribed to the progress of this git repo for a few years. Big fan of your work.

Just wanted to say, github has a milestones feature, where you can make a milestone, add a description, and add issues to it, so that when each issue is closed, the progress bar is going on and yeah its a cool feature especially for a roadmap to a release.

**Comment by garbear** [comment]
Cool, thanks for the idea! I'll look into migrating this issue to Milestones when I return to RP development... til then it's another bullet point in this issue :p
